#!/bin/bash
#
#   stackone   -  Copyright (c) 2008 stackone Corp.
#   ======
#
# stackone is a Virtualization management tool with a graphical user
# interface that allows for performing the standard set of VM operations
# (start, stop, pause, kill, shutdown, reboot, snapshot, etc...). It
# also attempts to simplify various aspects of VM lifecycle management.
#
#
# 
#
# author :
#

ping_node()
{
	count=$2
	if [ -z $1 ]; then
		echo "Invalid Address"
		return 1
	fi
	if [ -z $2 ]; then
		count=5
	fi
	echo "start pinging $1, $count times"

	ping -c $count $1
	ret=$?
	if [ $ret != 0 ]; then
	    echo "ERROR: Not able to ping $1."
	    return $ret
	fi
	echo "Successfully pinged $1"
}

ping_node "$@"
